# Generated by Django 5.1.1 on 2024-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_alter_explists_exp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explists',
            name='exp_file',
            field=models.FileField(upload_to='exp_lists/<bound method Field.__str__ of <django.db.models.fields.CharField>>/'),
        ),
    ]
